ALTER TABLE feedback
    MODIFY user_id INT UNSIGNED NULL,
    MODIFY rating TINYINT NULL,
    ADD COLUMN IF NOT EXISTS category VARCHAR(50) NOT NULL DEFAULT 'general' AFTER rating,
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(120) NULL AFTER user_id,
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(120) NULL AFTER first_name,
    ADD COLUMN IF NOT EXISTS email VARCHAR(180) NULL AFTER last_name,
    ADD COLUMN IF NOT EXISTS message TEXT NULL AFTER email,
    ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'new' AFTER message;
